#ra_addr
http://192.168.1.146/scep/
#ra_port
8080
#rootca_cert
-----BEGIN CERTIFICATE-----
MIIClTCCAfagAwIBAgIUZzNxspV7XfzXup5/lE8g942hBQswCgYIKoZIzj0EAwQw
XDELMAkGA1UEBhMCQ0ExIzAhBgNVBAoMGlJlc2VhcmNoIEluIE1vdGlvbiBMaW1p
dGVkMRMwEQYDVQQLDApCbGFja0JlcnJ5MRMwEQYDVQQDDApNeSBSb290IENBMB4X
DTI2MDQxNDE0NDgzOFoXDTQ2MDQwOTE0NDgzOFowXDELMAkGA1UEBhMCQ0ExIzAh
BgNVBAoMGlJlc2VhcmNoIEluIE1vdGlvbiBMaW1pdGVkMRMwEQYDVQQLDApCbGFj
a0JlcnJ5MRMwEQYDVQQDDApNeSBSb290IENBMIGbMBAGByqGSM49AgEGBSuBBAAj
A4GGAAQBbQN8T3YWCaGm134S5M8eXqknCdUp71xqtS86UtHJSo7b1BIXnASFwsfb
m2deo8kmmq0pinx1MJQadD4ybiWnm68A311ermj4ohm3Uobxq9veL9DedP89ZiJ/
hjBkY5eabob5P1lu9ea9QQ3lcNnsM7Bt0AYfUrbYMSowOE+SkRMFM5ajUzBRMB0G
A1UdDgQWBBSIGbEX4vjUsY3yz8CVlRoR01SxBTAfBgNVHSMEGDAWgBSIGbEX4vjU
sY3yz8CVlRoR01SxBTAPBgNVHRMBAf8EBTADAQH/MAoGCCqGSM49BAMEA4GMADCB
iAJCAdyTBGbAY84SJKLgWIr3NMUPXfXxepwbwlWcEksbgvLOL74oz+ey4wdQ7pGL
O0CgsHSzDWR1j4BmWKxIos1LDxQ5AkIBrACKJitdWwSulZOvzZzEtG+sBmx3MrIj
YMOC5njqyT+tMKTINP6zdnUjCunyhkG3TwSMvHogP7tMadFnExMrAOw=
-----END CERTIFICATE-----
#subca_cert
-----BEGIN CERTIFICATE-----
MIICiTCCAeugAwIBAgIUa0DGdB+jOOTRrDtl4ytYn9a1bXMwCgYIKoZIzj0EAwMw
XDELMAkGA1UEBhMCQ0ExIzAhBgNVBAoMGlJlc2VhcmNoIEluIE1vdGlvbiBMaW1p
dGVkMRMwEQYDVQQLDApCbGFja0JlcnJ5MRMwEQYDVQQDDApNeSBSb290IENBMB4X
DTI2MDQxNDE0NDgzOFoXDTM2MDQxMTE0NDgzOFowZDELMAkGA1UEBhMCQ0ExIzAh
BgNVBAoMGlJlc2VhcmNoIEluIE1vdGlvbiBMaW1pdGVkMRMwEQYDVQQLDApCbGFj
a0JlcnJ5MRswGQYDVQQDDBJNeSBJbnRlcm1lZGlhdGUgQ0EwdjAQBgcqhkjOPQIB
BgUrgQQAIgNiAAR4N8w+bWP8lGg9bXpq0bWInXGh2mruH/zFfUwXHlg/jMunevmi
lLc/GWFXXb1p3sThACrfBBJhuwsEporUa1Y9vHceLkwmbkyALkxy73AmJt7Tgofp
0FqEs9vUxa0aUnqjZjBkMB0GA1UdDgQWBBQfzokAYdL6JoRNZg7hLaLZTGmYITAf
BgNVHSMEGDAWgBSIGbEX4vjUsY3yz8CVlRoR01SxBTASBgNVHRMBAf8ECDAGAQH/
AgEAMA4GA1UdDwEB/wQEAwIBhjAKBggqhkjOPQQDAwOBiwAwgYcCQgHM+t9NDBSD
pGmlbytk/AeDezOA6MEOjavVncJbjfF+R8GPvihlUm/OvFKdN5TmNVYvW4cot1xO
NzZ3KRcMMVL7LQJBB5GtH11ZOaA2EJcqaV7ZN2Q8K24Wrmkom4j8Lls9abdEjKrh
h337m4dfXHYBStUMurgXrxI3c42P/mefMtf7qmU=
-----END CERTIFICATE-----
#ra_cert
-----BEGIN CERTIFICATE-----
MIICVTCCAdugAwIBAgIUbxKPmImBmz3OpDJHykCQS0VFWXEwCgYIKoZIzj0EAwIw
ZDELMAkGA1UEBhMCQ0ExIzAhBgNVBAoMGlJlc2VhcmNoIEluIE1vdGlvbiBMaW1p
dGVkMRMwEQYDVQQLDApCbGFja0JlcnJ5MRswGQYDVQQDDBJNeSBJbnRlcm1lZGlh
dGUgQ0EwHhcNMjYwNDE0MTQ0ODM4WhcNMzYwNDExMTQ0ODM4WjBXMQswCQYDVQQG
EwJDQTEjMCEGA1UECgwaUmVzZWFyY2ggSW4gTW90aW9uIExpbWl0ZWQxEzARBgNV
BAsMCkJsYWNrQmVycnkxDjAMBgNVBAMMBU15IFJBMFkwEwYHKoZIzj0CAQYIKoZI
zj0DAQcDQgAEgxe/UEjuUi8h11YXRs+KE+ZW/5gsWfgzF6bw4KSHzsPizZxHTpqj
WQd60mRuZPey/S7DnupJVwc1alBeNL67HqN4MHYwHQYDVR0OBBYEFHoSUDKg/hWH
DsGrdxhjoMdv1mSbMB8GA1UdIwQYMBaAFB/OiQBh0vomhE1mDuEtotlMaZghMAwG
A1UdEwEB/wQCMAAwDgYDVR0PAQH/BAQDAgWgMBYGA1UdJQEB/wQMMAoGCCsGAQUF
BwMCMAoGCCqGSM49BAMCA2gAMGUCMGaegDWWJzuPIkHqLBFAlu0H5L3D0PT26+df
oIF/xOK+skL8TCWkHf7bzoFN6vzqEQIxAMMMCPbEMkqnk4UCAzKH+zA8S9XlzmIZ
A15rDrXm84mnAohwcPiYrDzgdVnTnQNjzg==
-----END CERTIFICATE-----
#
